export {default as Search} from './search/Search'
export {default as AuthorProfile} from './profile/AuthorProfile'
export {default as DepartmentProfile} from './department/DepartmentProfile'
export {default as About} from './about/About'
export {default as WiserStatistics} from './statistics/WiserStatistics'
